[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "python-educator"
source = "."

[services.variables]
PORT = "8501"